order-port: 26734
raft-port: 27238
order-replication-factor: 3
order-batching-interval: 1ms
order-0-ip: "10.10.1.1"
order-1-ip: "10.10.1.2"
order-2-ip: "10.10.1.3"

data-port: 23282
data-replication-factor: 3
data-batching-interval: 1ms
data-0-0-ip: "10.10.1.4"
data-0-1-ip: "10.10.1.5"
data-0-2-ip: "10.10.1.6"

disc-port: 23472
disc-ip: "10.10.1.4"