order-port: 26733
raft-port: 27238
order-replication-factor: 3
order-batching-interval: 10ms
order-0-ip: "10.10.1.1"
order-1-ip: "10.10.1.5"
order-2-ip: "10.10.1.6"

data-port: 23282
data-replication-factor: 2
data-batching-interval: 10ms
data-0-0-ip: "10.10.1.7"
data-0-1-ip: "10.10.1.8"

disc-port: 23472
disc-ip: "10.10.1.7"