namespace: scalogger

order-port: 26733
raft-port: 27238
order-replication-factor: 3
order-batching-interval: 1000ms

data-port: 23282
data-replication-factor: 2
data-batching-interval: 1000ms
order-addr: 127.0.0.1:26733

discovery-addr: 127.0.0.1:23472
