order-port: 26733
raft-port: 27238
order-replication-factor: 3
order-batching-interval: 0.1ms
order-0-ip: "10.10.1.16"
order-1-ip: "10.10.1.12"
order-2-ip: "10.10.1.13"

data-port: 23282
data-replication-factor: 2
data-batching-interval: 0.1ms
data-0-0-ip: "10.10.1.15"
data-0-1-ip: "10.10.1.14"
# data-1-0-ip: "10.10.1.10"
# data-1-1-ip: "10.10.1.11"

disc-port: 23472
disc-ip: "10.10.1.15"