namespace: scalogger

order-port: 26733
order-replication-factor: 1
order-batching-interval: 1000ms

data-replication-factor: 2
data-batching-interval: 1000ms
order-addr: 127.0.0.1:26733
data-peers: 127.0.0.1:23282,127.0.0.1:23283
