// Code generated by protoc-gen-go. DO NOT EDIT.
// source: orderpb/order.proto

package orderpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Feedback struct {
	FixedLag             bool     `protobuf:"varint,1,opt,name=fixedLag,proto3" json:"fixedLag,omitempty"`
	NumHoles             int64    `protobuf:"varint,2,opt,name=numHoles,proto3" json:"numHoles,omitempty"`
	QueueLength          int64    `protobuf:"varint,3,opt,name=queueLength,proto3" json:"queueLength,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Feedback) Reset()         { *m = Feedback{} }
func (m *Feedback) String() string { return proto.CompactTextString(m) }
func (*Feedback) ProtoMessage()    {}
func (*Feedback) Descriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{0}
}

func (m *Feedback) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Feedback.Unmarshal(m, b)
}
func (m *Feedback) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Feedback.Marshal(b, m, deterministic)
}
func (m *Feedback) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Feedback.Merge(m, src)
}
func (m *Feedback) XXX_Size() int {
	return xxx_messageInfo_Feedback.Size(m)
}
func (m *Feedback) XXX_DiscardUnknown() {
	xxx_messageInfo_Feedback.DiscardUnknown(m)
}

var xxx_messageInfo_Feedback proto.InternalMessageInfo

func (m *Feedback) GetFixedLag() bool {
	if m != nil {
		return m.FixedLag
	}
	return false
}

func (m *Feedback) GetNumHoles() int64 {
	if m != nil {
		return m.NumHoles
	}
	return 0
}

func (m *Feedback) GetQueueLength() int64 {
	if m != nil {
		return m.QueueLength
	}
	return 0
}

type Control struct {
	Lag                  map[int32]int64 `protobuf:"bytes,1,rep,name=lag,proto3" json:"lag,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Control) Reset()         { *m = Control{} }
func (m *Control) String() string { return proto.CompactTextString(m) }
func (*Control) ProtoMessage()    {}
func (*Control) Descriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{1}
}

func (m *Control) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Control.Unmarshal(m, b)
}
func (m *Control) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Control.Marshal(b, m, deterministic)
}
func (m *Control) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Control.Merge(m, src)
}
func (m *Control) XXX_Size() int {
	return xxx_messageInfo_Control.Size(m)
}
func (m *Control) XXX_DiscardUnknown() {
	xxx_messageInfo_Control.DiscardUnknown(m)
}

var xxx_messageInfo_Control proto.InternalMessageInfo

func (m *Control) GetLag() map[int32]int64 {
	if m != nil {
		return m.Lag
	}
	return nil
}

type LocalCut struct {
	ShardID              int32     `protobuf:"varint,1,opt,name=shardID,proto3" json:"shardID,omitempty"`
	LocalReplicaID       int32     `protobuf:"varint,2,opt,name=localReplicaID,proto3" json:"localReplicaID,omitempty"`
	Cut                  []int64   `protobuf:"varint,3,rep,packed,name=cut,proto3" json:"cut,omitempty"`
	Quota                int64     `protobuf:"varint,4,opt,name=quota,proto3" json:"quota,omitempty"`
	LocalCutNum          int64     `protobuf:"varint,5,opt,name=localCutNum,proto3" json:"localCutNum,omitempty"`
	WindowNum            int64     `protobuf:"varint,6,opt,name=windowNum,proto3" json:"windowNum,omitempty"`
	Feedback             *Feedback `protobuf:"bytes,7,opt,name=feedback,proto3" json:"feedback,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LocalCut) Reset()         { *m = LocalCut{} }
func (m *LocalCut) String() string { return proto.CompactTextString(m) }
func (*LocalCut) ProtoMessage()    {}
func (*LocalCut) Descriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{2}
}

func (m *LocalCut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocalCut.Unmarshal(m, b)
}
func (m *LocalCut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocalCut.Marshal(b, m, deterministic)
}
func (m *LocalCut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocalCut.Merge(m, src)
}
func (m *LocalCut) XXX_Size() int {
	return xxx_messageInfo_LocalCut.Size(m)
}
func (m *LocalCut) XXX_DiscardUnknown() {
	xxx_messageInfo_LocalCut.DiscardUnknown(m)
}

var xxx_messageInfo_LocalCut proto.InternalMessageInfo

func (m *LocalCut) GetShardID() int32 {
	if m != nil {
		return m.ShardID
	}
	return 0
}

func (m *LocalCut) GetLocalReplicaID() int32 {
	if m != nil {
		return m.LocalReplicaID
	}
	return 0
}

func (m *LocalCut) GetCut() []int64 {
	if m != nil {
		return m.Cut
	}
	return nil
}

func (m *LocalCut) GetQuota() int64 {
	if m != nil {
		return m.Quota
	}
	return 0
}

func (m *LocalCut) GetLocalCutNum() int64 {
	if m != nil {
		return m.LocalCutNum
	}
	return 0
}

func (m *LocalCut) GetWindowNum() int64 {
	if m != nil {
		return m.WindowNum
	}
	return 0
}

func (m *LocalCut) GetFeedback() *Feedback {
	if m != nil {
		return m.Feedback
	}
	return nil
}

type LocalCuts struct {
	Cuts                 []*LocalCut `protobuf:"bytes,1,rep,name=cuts,proto3" json:"cuts,omitempty"`
	FixingLag            bool        `protobuf:"varint,2,opt,name=fixingLag,proto3" json:"fixingLag,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *LocalCuts) Reset()         { *m = LocalCuts{} }
func (m *LocalCuts) String() string { return proto.CompactTextString(m) }
func (*LocalCuts) ProtoMessage()    {}
func (*LocalCuts) Descriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{3}
}

func (m *LocalCuts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocalCuts.Unmarshal(m, b)
}
func (m *LocalCuts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocalCuts.Marshal(b, m, deterministic)
}
func (m *LocalCuts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocalCuts.Merge(m, src)
}
func (m *LocalCuts) XXX_Size() int {
	return xxx_messageInfo_LocalCuts.Size(m)
}
func (m *LocalCuts) XXX_DiscardUnknown() {
	xxx_messageInfo_LocalCuts.DiscardUnknown(m)
}

var xxx_messageInfo_LocalCuts proto.InternalMessageInfo

func (m *LocalCuts) GetCuts() []*LocalCut {
	if m != nil {
		return m.Cuts
	}
	return nil
}

func (m *LocalCuts) GetFixingLag() bool {
	if m != nil {
		return m.FixingLag
	}
	return false
}

type CommittedCut struct {
	StartGSN int64 `protobuf:"varint,1,opt,name=startGSN,proto3" json:"startGSN,omitempty"`
	// from globalReplicaID to each cut entry
	// globalReplicaID = shardID * numReplicas + localReplicaID
	Cut                  map[int32]int64 `protobuf:"bytes,2,rep,name=cut,proto3" json:"cut,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	ShardQuotas          map[int32]int64 `protobuf:"bytes,3,rep,name=shardQuotas,proto3" json:"shardQuotas,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	IsShardQuotaUpdated  bool            `protobuf:"varint,4,opt,name=isShardQuotaUpdated,proto3" json:"isShardQuotaUpdated,omitempty"`
	AdjustmentSignal     *Control        `protobuf:"bytes,5,opt,name=adjustmentSignal,proto3" json:"adjustmentSignal,omitempty"`
	WindowNum            int64           `protobuf:"varint,6,opt,name=windowNum,proto3" json:"windowNum,omitempty"`
	ViewID               int32           `protobuf:"varint,7,opt,name=viewID,proto3" json:"viewID,omitempty"`
	WindowStartGSN       int64           `protobuf:"varint,8,opt,name=windowStartGSN,proto3" json:"windowStartGSN,omitempty"`
	PrevCut              map[int32]int64 `protobuf:"bytes,9,rep,name=prevCut,proto3" json:"prevCut,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CommittedCut) Reset()         { *m = CommittedCut{} }
func (m *CommittedCut) String() string { return proto.CompactTextString(m) }
func (*CommittedCut) ProtoMessage()    {}
func (*CommittedCut) Descriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{4}
}

func (m *CommittedCut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommittedCut.Unmarshal(m, b)
}
func (m *CommittedCut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommittedCut.Marshal(b, m, deterministic)
}
func (m *CommittedCut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommittedCut.Merge(m, src)
}
func (m *CommittedCut) XXX_Size() int {
	return xxx_messageInfo_CommittedCut.Size(m)
}
func (m *CommittedCut) XXX_DiscardUnknown() {
	xxx_messageInfo_CommittedCut.DiscardUnknown(m)
}

var xxx_messageInfo_CommittedCut proto.InternalMessageInfo

func (m *CommittedCut) GetStartGSN() int64 {
	if m != nil {
		return m.StartGSN
	}
	return 0
}

func (m *CommittedCut) GetCut() map[int32]int64 {
	if m != nil {
		return m.Cut
	}
	return nil
}

func (m *CommittedCut) GetShardQuotas() map[int32]int64 {
	if m != nil {
		return m.ShardQuotas
	}
	return nil
}

func (m *CommittedCut) GetIsShardQuotaUpdated() bool {
	if m != nil {
		return m.IsShardQuotaUpdated
	}
	return false
}

func (m *CommittedCut) GetAdjustmentSignal() *Control {
	if m != nil {
		return m.AdjustmentSignal
	}
	return nil
}

func (m *CommittedCut) GetWindowNum() int64 {
	if m != nil {
		return m.WindowNum
	}
	return 0
}

func (m *CommittedCut) GetViewID() int32 {
	if m != nil {
		return m.ViewID
	}
	return 0
}

func (m *CommittedCut) GetWindowStartGSN() int64 {
	if m != nil {
		return m.WindowStartGSN
	}
	return 0
}

func (m *CommittedCut) GetPrevCut() map[int32]int64 {
	if m != nil {
		return m.PrevCut
	}
	return nil
}

type CommittedEntry struct {
	Seq                  int64          `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	ViewID               int32          `protobuf:"varint,2,opt,name=viewID,proto3" json:"viewID,omitempty"`
	CommittedCut         *CommittedCut  `protobuf:"bytes,3,opt,name=committedCut,proto3" json:"committedCut,omitempty"`
	FinalizeShards       *FinalizeEntry `protobuf:"bytes,4,opt,name=finalizeShards,proto3" json:"finalizeShards,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CommittedEntry) Reset()         { *m = CommittedEntry{} }
func (m *CommittedEntry) String() string { return proto.CompactTextString(m) }
func (*CommittedEntry) ProtoMessage()    {}
func (*CommittedEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{5}
}

func (m *CommittedEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommittedEntry.Unmarshal(m, b)
}
func (m *CommittedEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommittedEntry.Marshal(b, m, deterministic)
}
func (m *CommittedEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommittedEntry.Merge(m, src)
}
func (m *CommittedEntry) XXX_Size() int {
	return xxx_messageInfo_CommittedEntry.Size(m)
}
func (m *CommittedEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_CommittedEntry.DiscardUnknown(m)
}

var xxx_messageInfo_CommittedEntry proto.InternalMessageInfo

func (m *CommittedEntry) GetSeq() int64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *CommittedEntry) GetViewID() int32 {
	if m != nil {
		return m.ViewID
	}
	return 0
}

func (m *CommittedEntry) GetCommittedCut() *CommittedCut {
	if m != nil {
		return m.CommittedCut
	}
	return nil
}

func (m *CommittedEntry) GetFinalizeShards() *FinalizeEntry {
	if m != nil {
		return m.FinalizeShards
	}
	return nil
}

type FinalizeEntry struct {
	Limit                int32    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	ShardIDs             []int32  `protobuf:"varint,2,rep,packed,name=shardIDs,proto3" json:"shardIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FinalizeEntry) Reset()         { *m = FinalizeEntry{} }
func (m *FinalizeEntry) String() string { return proto.CompactTextString(m) }
func (*FinalizeEntry) ProtoMessage()    {}
func (*FinalizeEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{6}
}

func (m *FinalizeEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinalizeEntry.Unmarshal(m, b)
}
func (m *FinalizeEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinalizeEntry.Marshal(b, m, deterministic)
}
func (m *FinalizeEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinalizeEntry.Merge(m, src)
}
func (m *FinalizeEntry) XXX_Size() int {
	return xxx_messageInfo_FinalizeEntry.Size(m)
}
func (m *FinalizeEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_FinalizeEntry.DiscardUnknown(m)
}

var xxx_messageInfo_FinalizeEntry proto.InternalMessageInfo

func (m *FinalizeEntry) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *FinalizeEntry) GetShardIDs() []int32 {
	if m != nil {
		return m.ShardIDs
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{7}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type FinalizeRequest struct {
	ShardID              int32    `protobuf:"varint,1,opt,name=shardID,proto3" json:"shardID,omitempty"`
	LocalReplicaID       int32    `protobuf:"varint,2,opt,name=localReplicaID,proto3" json:"localReplicaID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FinalizeRequest) Reset()         { *m = FinalizeRequest{} }
func (m *FinalizeRequest) String() string { return proto.CompactTextString(m) }
func (*FinalizeRequest) ProtoMessage()    {}
func (*FinalizeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{8}
}

func (m *FinalizeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinalizeRequest.Unmarshal(m, b)
}
func (m *FinalizeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinalizeRequest.Marshal(b, m, deterministic)
}
func (m *FinalizeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinalizeRequest.Merge(m, src)
}
func (m *FinalizeRequest) XXX_Size() int {
	return xxx_messageInfo_FinalizeRequest.Size(m)
}
func (m *FinalizeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FinalizeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FinalizeRequest proto.InternalMessageInfo

func (m *FinalizeRequest) GetShardID() int32 {
	if m != nil {
		return m.ShardID
	}
	return 0
}

func (m *FinalizeRequest) GetLocalReplicaID() int32 {
	if m != nil {
		return m.LocalReplicaID
	}
	return 0
}

func init() {
	proto.RegisterType((*Feedback)(nil), "orderpb.Feedback")
	proto.RegisterType((*Control)(nil), "orderpb.Control")
	proto.RegisterMapType((map[int32]int64)(nil), "orderpb.Control.LagEntry")
	proto.RegisterType((*LocalCut)(nil), "orderpb.LocalCut")
	proto.RegisterType((*LocalCuts)(nil), "orderpb.LocalCuts")
	proto.RegisterType((*CommittedCut)(nil), "orderpb.CommittedCut")
	proto.RegisterMapType((map[int32]int64)(nil), "orderpb.CommittedCut.CutEntry")
	proto.RegisterMapType((map[int32]int64)(nil), "orderpb.CommittedCut.PrevCutEntry")
	proto.RegisterMapType((map[int32]int64)(nil), "orderpb.CommittedCut.ShardQuotasEntry")
	proto.RegisterType((*CommittedEntry)(nil), "orderpb.CommittedEntry")
	proto.RegisterType((*FinalizeEntry)(nil), "orderpb.FinalizeEntry")
	proto.RegisterType((*Empty)(nil), "orderpb.Empty")
	proto.RegisterType((*FinalizeRequest)(nil), "orderpb.FinalizeRequest")
}

func init() { proto.RegisterFile("orderpb/order.proto", fileDescriptor_87a9833f63666870) }

var fileDescriptor_87a9833f63666870 = []byte{
	// 710 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x95, 0xff, 0x4e, 0x13, 0x41,
	0x10, 0xc7, 0xb9, 0x1e, 0xd7, 0x1e, 0x73, 0xd8, 0xd4, 0x45, 0xf1, 0x6c, 0x8c, 0x69, 0x2e, 0x91,
	0x5c, 0x62, 0x2c, 0x78, 0x1a, 0xa3, 0x48, 0x48, 0x4c, 0x01, 0x21, 0x69, 0x10, 0xb7, 0xf1, 0x01,
	0x96, 0xde, 0xb6, 0xac, 0xdc, 0x2f, 0xee, 0xf6, 0x28, 0xf8, 0x5e, 0xbe, 0x8e, 0xff, 0x98, 0xf8,
	0x1c, 0x66, 0xf7, 0x7e, 0xd2, 0xd6, 0x18, 0xfe, 0xea, 0xcd, 0xcc, 0x77, 0x6e, 0x76, 0x3e, 0xb3,
	0x73, 0x85, 0x8d, 0x30, 0x76, 0x69, 0x1c, 0x9d, 0x6f, 0xcb, 0xdf, 0x7e, 0x14, 0x87, 0x3c, 0x44,
	0xad, 0xdc, 0x69, 0xb9, 0xa0, 0x1f, 0x51, 0xea, 0x9e, 0x93, 0xf1, 0x25, 0xea, 0x82, 0x3e, 0x61,
	0x37, 0xd4, 0x1d, 0x92, 0xa9, 0xa9, 0xf4, 0x14, 0x5b, 0xc7, 0xa5, 0x2d, 0x62, 0x41, 0xea, 0x1f,
	0x87, 0x1e, 0x4d, 0xcc, 0x46, 0x4f, 0xb1, 0x55, 0x5c, 0xda, 0xa8, 0x07, 0xc6, 0x55, 0x4a, 0x53,
	0x3a, 0xa4, 0xc1, 0x94, 0x5f, 0x98, 0xaa, 0x0c, 0xd7, 0x5d, 0x56, 0x00, 0xad, 0x41, 0x18, 0xf0,
	0x38, 0xf4, 0xd0, 0x4b, 0x50, 0x3d, 0xf9, 0x7e, 0xd5, 0x36, 0x9c, 0xa7, 0xfd, 0xfc, 0x1c, 0xfd,
	0x3c, 0xdc, 0x1f, 0x92, 0xe9, 0x61, 0xc0, 0xe3, 0x5b, 0x2c, 0x54, 0xdd, 0x77, 0xa0, 0x17, 0x0e,
	0xd4, 0x01, 0xf5, 0x92, 0xde, 0xca, 0x83, 0x69, 0x58, 0x3c, 0xa2, 0x47, 0xa0, 0x5d, 0x13, 0x2f,
	0xa5, 0xf9, 0x81, 0x32, 0x63, 0xb7, 0xf1, 0x5e, 0xb1, 0x7e, 0x2b, 0xa0, 0x0f, 0xc3, 0x31, 0xf1,
	0x06, 0x29, 0x47, 0x26, 0xb4, 0x92, 0x0b, 0x12, 0xbb, 0x27, 0x07, 0x79, 0x72, 0x61, 0xa2, 0x2d,
	0x68, 0x7b, 0x42, 0x85, 0x69, 0xe4, 0xb1, 0x31, 0x39, 0x39, 0x90, 0x6f, 0xd2, 0xf0, 0x9c, 0x57,
	0x94, 0x1e, 0xa7, 0xdc, 0x54, 0x7b, 0xaa, 0xad, 0x62, 0xf1, 0x28, 0x4a, 0x5f, 0xa5, 0x21, 0x27,
	0xe6, 0x6a, 0x56, 0x5a, 0x1a, 0x02, 0x84, 0x97, 0x57, 0x3d, 0x4d, 0x7d, 0x53, 0xcb, 0x40, 0xd4,
	0x5c, 0xe8, 0x19, 0xac, 0xcd, 0x58, 0xe0, 0x86, 0x33, 0x11, 0x6f, 0xca, 0x78, 0xe5, 0x40, 0xaf,
	0x40, 0x9f, 0xe4, 0xc3, 0x30, 0x5b, 0x3d, 0xc5, 0x36, 0x9c, 0x87, 0x25, 0xa0, 0x62, 0x4a, 0xb8,
	0x94, 0x58, 0x67, 0xb0, 0x56, 0x34, 0x99, 0xa0, 0x17, 0xb0, 0x3a, 0x4e, 0x79, 0x92, 0x83, 0xad,
	0xf2, 0x0a, 0x05, 0x96, 0x61, 0x71, 0x80, 0x09, 0xbb, 0x61, 0xc1, 0x54, 0x0c, 0xb9, 0x21, 0x87,
	0x5c, 0x39, 0xac, 0x3f, 0xab, 0xb0, 0x3e, 0x08, 0x7d, 0x9f, 0x71, 0x4e, 0x5d, 0xc1, 0xae, 0x0b,
	0x7a, 0xc2, 0x49, 0xcc, 0x3f, 0x8f, 0x4e, 0x25, 0x3c, 0x15, 0x97, 0x36, 0xda, 0xc9, 0xa8, 0x34,
	0x64, 0xc1, 0xe7, 0xb5, 0x49, 0x56, 0xf9, 0xfd, 0x41, 0xca, 0xf3, 0x71, 0x0a, 0x6a, 0xc7, 0x60,
	0x48, 0xf4, 0x5f, 0x05, 0xad, 0x44, 0xf2, 0x34, 0x9c, 0xad, 0xe5, 0x99, 0xa3, 0x4a, 0x98, 0xbd,
	0xa1, 0x9e, 0x8a, 0x76, 0x60, 0x83, 0x25, 0x95, 0xe4, 0x5b, 0xe4, 0x12, 0x4e, 0x5d, 0x39, 0x0d,
	0x1d, 0x2f, 0x0b, 0xa1, 0x3d, 0xe8, 0x10, 0xf7, 0x7b, 0x9a, 0x70, 0x9f, 0x06, 0x7c, 0xc4, 0xa6,
	0x01, 0xf1, 0xe4, 0x80, 0x0c, 0xa7, 0x33, 0x7f, 0x09, 0xf1, 0x82, 0xf2, 0x3f, 0x73, 0xdb, 0x84,
	0xe6, 0x35, 0xa3, 0xb3, 0x93, 0x03, 0x39, 0x35, 0x0d, 0xe7, 0x96, 0xb8, 0x5f, 0x99, 0x68, 0x54,
	0x30, 0xd4, 0x65, 0xea, 0x9c, 0x17, 0xed, 0x41, 0x2b, 0x8a, 0xe9, 0xf5, 0x20, 0xe5, 0xe6, 0x9a,
	0x64, 0x62, 0x2d, 0x67, 0x72, 0x96, 0x89, 0x32, 0x1e, 0x45, 0x8a, 0x58, 0x92, 0xc2, 0x79, 0x9f,
	0x25, 0xe9, 0xee, 0x43, 0x67, 0x1e, 0xf2, 0xbd, 0xf2, 0x77, 0x61, 0xbd, 0x7e, 0xa0, 0x7b, 0x2d,
	0xe8, 0x4f, 0x05, 0xda, 0x65, 0x6b, 0x65, 0x7a, 0x42, 0xaf, 0xf2, 0x5b, 0x26, 0x1e, 0x6b, 0x58,
	0x1b, 0x77, 0xb0, 0x7e, 0x80, 0xf5, 0x71, 0x0d, 0x8b, 0xfc, 0xe0, 0x18, 0xce, 0xe3, 0xa5, 0xcc,
	0xf0, 0x1d, 0x29, 0xda, 0x87, 0xf6, 0x84, 0x05, 0xc4, 0x63, 0x3f, 0xa8, 0xec, 0x3d, 0x91, 0x57,
	0xc6, 0x70, 0x36, 0xab, 0x3d, 0xcb, 0xc3, 0x19, 0xe4, 0x39, 0xb5, 0xf5, 0x09, 0x1e, 0xdc, 0x11,
	0x88, 0x16, 0x3d, 0xe6, 0x33, 0x9e, 0xb7, 0x9d, 0x19, 0x72, 0x6d, 0xb2, 0x6f, 0x4c, 0x22, 0xf7,
	0x43, 0xc3, 0xa5, 0x6d, 0xb5, 0x40, 0x3b, 0xf4, 0x23, 0x7e, 0xeb, 0xfc, 0x52, 0x40, 0xfb, 0x22,
	0xaa, 0xa2, 0x8f, 0xd0, 0xc4, 0x34, 0x0a, 0x63, 0x8e, 0xd0, 0xc2, 0xde, 0x26, 0xdd, 0x27, 0x8b,
	0x8d, 0xc9, 0xda, 0xd6, 0x8a, 0xad, 0xec, 0x28, 0x68, 0x1b, 0x74, 0x4c, 0xa7, 0x2c, 0xe1, 0x34,
	0x46, 0x8b, 0x6b, 0xdf, 0x6d, 0x97, 0x2e, 0x59, 0xd5, 0x5a, 0x41, 0xaf, 0xa1, 0x75, 0x14, 0xc6,
	0x33, 0x12, 0xbb, 0x4b, 0xcb, 0x2d, 0x24, 0xd8, 0x0a, 0x7a, 0x0b, 0x7a, 0xd1, 0x36, 0xfa, 0x07,
	0xaa, 0xc5, 0xbc, 0xf3, 0xa6, 0xfc, 0xaf, 0x79, 0xf3, 0x37, 0x00, 0x00, 0xff, 0xff, 0x71, 0x70,
	0xf2, 0xf8, 0x82, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrderClient is the client API for Order service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderClient interface {
	Report(ctx context.Context, opts ...grpc.CallOption) (Order_ReportClient, error)
	Register(ctx context.Context, in *LocalCut, opts ...grpc.CallOption) (*Empty, error)
	Forward(ctx context.Context, opts ...grpc.CallOption) (Order_ForwardClient, error)
	Finalize(ctx context.Context, in *FinalizeRequest, opts ...grpc.CallOption) (*Empty, error)
}

type orderClient struct {
	cc *grpc.ClientConn
}

func NewOrderClient(cc *grpc.ClientConn) OrderClient {
	return &orderClient{cc}
}

func (c *orderClient) Report(ctx context.Context, opts ...grpc.CallOption) (Order_ReportClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Order_serviceDesc.Streams[0], "/orderpb.Order/Report", opts...)
	if err != nil {
		return nil, err
	}
	x := &orderReportClient{stream}
	return x, nil
}

type Order_ReportClient interface {
	Send(*LocalCuts) error
	Recv() (*CommittedEntry, error)
	grpc.ClientStream
}

type orderReportClient struct {
	grpc.ClientStream
}

func (x *orderReportClient) Send(m *LocalCuts) error {
	return x.ClientStream.SendMsg(m)
}

func (x *orderReportClient) Recv() (*CommittedEntry, error) {
	m := new(CommittedEntry)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *orderClient) Register(ctx context.Context, in *LocalCut, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/orderpb.Order/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) Forward(ctx context.Context, opts ...grpc.CallOption) (Order_ForwardClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Order_serviceDesc.Streams[1], "/orderpb.Order/Forward", opts...)
	if err != nil {
		return nil, err
	}
	x := &orderForwardClient{stream}
	return x, nil
}

type Order_ForwardClient interface {
	Send(*LocalCuts) error
	CloseAndRecv() (*Empty, error)
	grpc.ClientStream
}

type orderForwardClient struct {
	grpc.ClientStream
}

func (x *orderForwardClient) Send(m *LocalCuts) error {
	return x.ClientStream.SendMsg(m)
}

func (x *orderForwardClient) CloseAndRecv() (*Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *orderClient) Finalize(ctx context.Context, in *FinalizeRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/orderpb.Order/Finalize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServer is the server API for Order service.
type OrderServer interface {
	Report(Order_ReportServer) error
	Register(context.Context, *LocalCut) (*Empty, error)
	Forward(Order_ForwardServer) error
	Finalize(context.Context, *FinalizeRequest) (*Empty, error)
}

// UnimplementedOrderServer can be embedded to have forward compatible implementations.
type UnimplementedOrderServer struct {
}

func (*UnimplementedOrderServer) Report(srv Order_ReportServer) error {
	return status.Errorf(codes.Unimplemented, "method Report not implemented")
}
func (*UnimplementedOrderServer) Register(ctx context.Context, req *LocalCut) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedOrderServer) Forward(srv Order_ForwardServer) error {
	return status.Errorf(codes.Unimplemented, "method Forward not implemented")
}
func (*UnimplementedOrderServer) Finalize(ctx context.Context, req *FinalizeRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Finalize not implemented")
}

func RegisterOrderServer(s *grpc.Server, srv OrderServer) {
	s.RegisterService(&_Order_serviceDesc, srv)
}

func _Order_Report_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OrderServer).Report(&orderReportServer{stream})
}

type Order_ReportServer interface {
	Send(*CommittedEntry) error
	Recv() (*LocalCuts, error)
	grpc.ServerStream
}

type orderReportServer struct {
	grpc.ServerStream
}

func (x *orderReportServer) Send(m *CommittedEntry) error {
	return x.ServerStream.SendMsg(m)
}

func (x *orderReportServer) Recv() (*LocalCuts, error) {
	m := new(LocalCuts)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Order_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocalCut)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/orderpb.Order/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).Register(ctx, req.(*LocalCut))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_Forward_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OrderServer).Forward(&orderForwardServer{stream})
}

type Order_ForwardServer interface {
	SendAndClose(*Empty) error
	Recv() (*LocalCuts, error)
	grpc.ServerStream
}

type orderForwardServer struct {
	grpc.ServerStream
}

func (x *orderForwardServer) SendAndClose(m *Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *orderForwardServer) Recv() (*LocalCuts, error) {
	m := new(LocalCuts)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Order_Finalize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinalizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).Finalize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/orderpb.Order/Finalize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).Finalize(ctx, req.(*FinalizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Order_serviceDesc = grpc.ServiceDesc{
	ServiceName: "orderpb.Order",
	HandlerType: (*OrderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Order_Register_Handler,
		},
		{
			MethodName: "Finalize",
			Handler:    _Order_Finalize_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Report",
			Handler:       _Order_Report_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Forward",
			Handler:       _Order_Forward_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "orderpb/order.proto",
}
